package com.r786.studyflow.modules.audit.entity;

public enum AuditAction {
    REGISTER_INITIATED, OTP_VERIFIED, REGISTRATION_COMPLETED,
    LOGIN_SUCCESS, LOGIN_FAILED,USER_AUTHENTICATED,
    PASSWORD_RESET_REQUESTED,PASSWORD_RESET_COMPLETED,PROFILE_UPDATED,

    EMAIL_UPDATE_INITIATED,
    EMAIL_UPDATE_OLD_VERIFIED,
    EMAIL_UPDATE_COMPLETED,

    COURSE_CREATED, COURSE_DELETED, STUDENT_ENROLLED,

    // Quiz Module (Upcoming)
    QUIZ_SUBMITTED, QUIZ_CREATED
}

